[package]
name = "bitcoin-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
warp = "0.3"
regex = "1.0"

[[bin]]
name = "debugger"
path = "src/main.rs"