[package]
name = "bitcoin-monitor"
version = "2.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.20"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
warp = "0.3"
regex = "1.0"
futures-util = "0.3"

[[bin]]
name = "monitor"
path = "src/main.rs"

[lib]
name = "bitcoin_monitor"
path = "src/lib.rs"